### ISSUE TITLE
Using Application via network share 

### ISSUE THREAD

**Issue by SohilAhmed** [WhatsAppNETClient/WhatsAppNETClient2#1]
I've tried to use the Application via a network shared folder, on StartUp form app just helds up On "Wait" and doesn't move to next step. Works perfect on Local system though, need some work on Network Shaded folder and even if Folder is accessed by using network shaded path on Local computer app doesn't connect.

**Comment by k4m4r82** [comment]
What folder do you want to share?

**Comment by SohilAhmed** [comment]
In order to add this SDK to an existing project I need to Share this over the Network. Using one single Server and login (QR scan), multiple users would be able to send files and text.

**Comment by SohilAhmed** [comment]
Hello is there any update to this Issue???

**Comment by WhatsAppNETClient** [comment]
It's not a bug, so it really can't be done. You have to use another approach. Examples like this:

![arsitektur](https://user-images.githubusercontent.com/67818764/131766985-2961432b-592e-4c26-b178-c1c1e415bb6d.JPG)

So you create two separate applications, a server and a client that communicate using the socket or websocket protocol. The server application is responsible for communicating with WhatsApp
