### ISSUE TITLE
WA Boot Error setelah Scan QRCode

### ISSUE THREAD

**Issue by IKHWAN619** [WhatsAppNETClient/WhatsAppNETClient2#10]
Suhu kok sejak minggu 28-11-2021 Koneksinya Setelah scann QRCode kemudian error yaa...
apakah ada update terbaru dan ada langkah kusus lain untuk mengkoneksikan WA Boot nya...?
saya sudah coba ke 2 PC hasilnya sama...
saya jga sdah cba yg versi sebelum ada list menu dan button dan versi terbaru hasilnya masih sama...

terimakasih banyak min.. smoga ilmunya berkah dan selalu banyak rizkinya..aamiin

**Comment by WhatsAppNETClient** [comment]
Coba diupdate om utk repo WhatsAppNETAPINodeJs, langkah-langkahnya bisa cek di http://wa-net.coding4ever.net/#update
