### ISSUE TITLE
ambil data inbox dan outbox 

### ISSUE THREAD

**Issue by IKHWAN619** [WhatsAppNETClient/WhatsAppNETClient2#11]
Assalamualaikum Bapak Rudi...
apakah bisa mengkoneksikan wa ke database...
misalkan saya mau ambil inbox dan outbox kemudian saya masukan ke database..
mohon pencerahannya...
smoga selalu dilimpahkan Rizky buat Bapak Rudi...
trimakasih...

**Comment by WhatsAppNETClient** [comment]
Waalaikumussalam

Sudah ada methodnya om, jadi om tinggal kombinasikan method `GetContacts` dan `GetAllMessage`

**Comment by IKHWAN619** [comment]
Baik Pak sudah saya pelajari dan alhamdulillah bisa..
mkasih Banyak Pak

**Comment by WhatsAppNETClient** [comment]
Sama2x om
