### ISSUE TITLE
Gagal Kirim Video

### ISSUE THREAD

**Issue by xxxmarkoxxx** [WhatsAppNETClient/WhatsAppNETClient2#12]
selamat sore om.
mau tanya, kalau untuk kirim video ad kriteria khusus gak videonya?
soalnya ane udah coba beberapa kali kirim video seperti di gambar tapi belum pernah berhasil.
mohon pencerahanya
tks om

![kirimviedo](https://user-images.githubusercontent.com/45991802/156736189-5295d96e-d7f6-4824-97f4-5807a55c13e1.jpg)

**Comment by WhatsAppNETClient** [comment]
Kode yg ini sudah diaktifkan om? 

https://github.com/WhatsAppNETClient/WhatsAppNETClient2/blob/c94a1c09c11b66dca8f8caaf3e4261d566a04848/src/DemoWhatsAppNETAPICSharp/FrmMain.cs#L53

**Comment by soporteLINSA** [comment]
La aplicación cuando se cierra y se vuelve a abrir se queda en Wait....
Algunas veces en el Autoreplay envia doble respuesta....

**Comment by soporteLINSA** [comment]
Hola
Es normal este error durante la instalación del WhatsAppNETAPINodeJs
https://drive.google.com/file/d/1uxnNRRyoXrzPdKCmEaVrCiPw7y5sSIp5/view?usp=sharing
saludos

**Comment by WhatsAppNETClient** [comment]
Hola @soporteLINSA 

Tal vez puedas volver a intentarlo desde cero (instalación nueva)

https://user-images.githubusercontent.com/67818764/156913854-c49c71cd-6dcd-47c5-86ae-c34c74fa8e28.mp4

**Comment by soporteLINSA** [comment]
Hola
Consulta exista alguna forma de poder utilizar la aplicación sin numero de Whatsapp, sin tener que enlazar mi número de teléfono a la aplicación....

saludos

**Comment by WhatsAppNETClient** [comment]
@soporteLINSA 

Pruebe la versión beta, ya no depende del teléfono inteligente, solo escanéelo una vez, después de eso, la aplicación aún puede ejecutarse incluso si el teléfono está apagado

**Comment by xxxmarkoxxx** [comment]
> Kode yg ini sudah diaktifkan om?
> 
> https://github.com/WhatsAppNETClient/WhatsAppNETClient2/blob/c94a1c09c11b66dca8f8caaf3e4261d566a04848/src/DemoWhatsAppNETAPICSharp/FrmMain.cs#L53
> 
> Lokasi chrome.exenya di sesuaikan lagi

ok om makasi, sudah bisa.
