### ISSUE TITLE
Soporte para WhatsAppNETClient usando como teléfono virtual con el emulador Bluestacks

### ISSUE THREAD

**Issue by soporteLINSA** [WhatsAppNETClient/WhatsAppNETClient2#14]
Hola
Consulta yo utilizo un  teléfono virtual con el emulador de Android Bluestack, Whatsapp y aplicación Whatsapp Windows. Es posible utilizar el teléfono virtualizado con WhatsAppNETClient y la aplicación de vb.net?
https://www.bluestacks.com/es/index.html
https://support.bluestacks.com/hc/es/articles/4402611273485-Instalador-offline-de-BlueStacks-5
saludos
![imagen](https://user-images.githubusercontent.com/99940112/157060483-f72251de-0132-4775-aa8e-df036f1f401d.png)
![imagen](https://user-images.githubusercontent.com/99940112/157060541-d7f858da-b74e-48da-b2fd-4e55aeca8f0f.png)
![imagen](https://user-images.githubusercontent.com/99940112/157060788-00093172-4184-40db-90db-926e36f87971.png)
![imagen](https://user-images.githubusercontent.com/99940112/157060997-afba6742-7707-4ba0-957f-d97fc87c5b3d.png)
![imagen](https://user-images.githubusercontent.com/99940112/157061051-88bfc1b6-54c0-4958-9c2a-d4b2ca974779.png)

**Comment by WhatsAppNETClient** [comment]
Si puede
