### ISSUE TITLE
Soporte para Whatsapp Business

### ISSUE THREAD

**Issue by soporteLINSA** [WhatsAppNETClient/WhatsAppNETClient2#15]
Hola
Consulta existe compatilidad con Whatsapp Business?
saludos
![imagen](https://user-images.githubusercontent.com/99940112/157062135-9cea6d53-4667-4b7a-86e1-0068227cc7e0.png)

**Comment by WhatsAppNETClient** [comment]
Lo siento, no tengo un número de Whatsapp Business, así que no puedo intentar
