### ISSUE TITLE
Error evaluation fail

### ISSUE THREAD

**Issue by soporteLINSA** [WhatsAppNETClient/WhatsAppNETClient2#17]
![imagen](https://user-images.githubusercontent.com/99940112/157354314-fc99827a-c87f-469c-8ffc-cdef263a12b7.png)

**Comment by soporteLINSA** [comment]
La primera vez enlaza facil y rapido....La segunda se queda enciclado o dura mucho tiempo...

**Comment by soporteLINSA** [comment]
![imagen](https://user-images.githubusercontent.com/99940112/157361223-621993ea-1a08-4ff7-bb85-c2b134e1c7f7.png)

**Comment by WhatsAppNETClient** [comment]
Hay un cambio en el método de autenticación en la biblioteca whatsapp-web.js, la solución:

1. Actualice la biblioteca nuget de WhatsApp
2. Volver a clonar el repositorio https://github.com/WhatsAppNETClient/WhatsAppNETAPINodeJs
3. Instalación de npm

**Comment by soporteLINSA** [comment]
Hola

Este es mi equipo:
Intel(R) Xeon(R) CPU E31220 @ 3.10GHz  
1T SSD Disco estado solido
16 GB Memoria Ram

Esta es la configuración:
Windows 10 Pro x64
Git-2.35.1.2-64-bit
Node.js-v16.14.0-x64
Microsoft Visual Studio Community Edition 2015
WhatsappNETAPI 2.8.1

Instalación pasos:
paso#1
cd..
cd..
git clone https://github.com/WhatsAppNETClient/WhatsAppNETAPINodeJs.git
![imagen](https://user-images.githubusercontent.com/99940112/157448892-8617916b-a2d8-4328-ac2a-75dbb873ddfd.png)

paso#2
cd WhatsAppNETAPINodeJs
npm install
npm start
![imagen](https://user-images.githubusercontent.com/99940112/157449406-19f581ee-7051-49e3-9b7c-109bb77683fb.png)

paso#3
cd..
git clone https://github.com/WhatsAppNETClient/WhatsAppNETClient2.git
![imagen](https://user-images.githubusercontent.com/99940112/157449681-0f07170a-a085-4213-ac52-d5db5fc30719.png)
![imagen](https://user-images.githubusercontent.com/99940112/157449899-104cc449-8288-4406-840d-1361c07d10c4.png)

paso#4
cd WhatsAppNETAPINodeJs
git pull
npm update whatsapp-web.js
![imagen](https://user-images.githubusercontent.com/99940112/157450173-243b3aca-744e-49ed-9fb0-5d284df4437a.png)

paso#5
![imagen](https://user-images.githubusercontent.com/99940112/157450343-859694bc-8351-4f08-af4e-1210486d60fd.png)
![imagen](https://user-images.githubusercontent.com/99940112/157450576-d4eca28d-368e-4d50-8b16-35f99aa189d7.png)
![imagen](https://user-images.githubusercontent.com/99940112/157450791-df682004-57bb-444b-95a0-bc9fdb56c688.png)

**Comment by WhatsAppNETClient** [comment]
intente ejecutar el comando nuevamente: `npm update whatsapp-web.js`

**Comment by soporteLINSA** [comment]
![imagen](https://user-images.githubusercontent.com/99940112/157683348-531bf417-ebfb-48e3-8400-589e966a05e6.png)

![imagen](https://user-images.githubusercontent.com/99940112/157683809-764cca31-b154-4e57-a948-a1a0e01efd26.png)

Igual se queda en Autenticado y de ahy no pasa....

**Comment by soporteLINSA** [comment]
Me sigue dando problemas para conectarse...

**Comment by soporteLINSA** [comment]
Me sigue dando problemas para conectarse...
Igual se queda en Autenticado y de ahy no pasa....

**Comment by soporteLINSA** [comment]
Hola
Me sigue dando problemas para conectarse...
Igual se queda en Autenticado y de ahy no pasa....
Cual cree que puede ser el problema...no logro que funcione....

**Comment by WhatsAppNETClient** [comment]
Para la última versión de [WhatsAppNETAPI](https://www.nuget.org/packages/WhatsAppNETAPI/2.8.1), la propiedad `Headless` ya está disponible, si se establece en falso, mostrará chrome browser, por lo que es posible que pueda ver lo que está sucediendo.

**Comment by soporteLINSA** [comment]
Hola y esto que me dice...
![imagen](https://user-images.githubusercontent.com/99940112/158034411-7fe018e1-2ff1-4fcf-bfa1-1ce95c8ee9a7.png)

Con propiedad Headless  en False el navegador Chrome se abre y se cierra inmediatamente, y en la carpeta C:\WhatsAppNETAPINodeJs\session aparece esto:
![imagen](https://user-images.githubusercontent.com/99940112/158034673-bda61c6b-283b-46cf-9782-7593ba0be163.png)

Cual seria el problema.....????

**Comment by WhatsAppNETClient** [comment]
@soporteLINSA 
¿Se ha solucionado este problema?

**Comment by soporteLINSA** [comment]
Hola
Si, Gracias

**Comment by WhatsAppNETClient** [comment]
de nada

**Comment by WhatsAppNETClient** [comment]
@Dieguit0Paz 

Vale, me alegro de que este proyecto te pueda ser útil.
