### ISSUE TITLE
Update WhatsApp BETA

### ISSUE THREAD

**Issue by rezkiye** [WhatsAppNETClient/WhatsAppNETClient2#2]
Gan tolong di update buat bisa runing di whatsapp beta. banyak fitur di whatsapp beta gan. salah satunya bisa run whastapp web di beberapa device sekaligus dan gak waktu hp posisi off / tidak terkoneksi internet pun whatsapp web tetap jalan. terima kasih.

**Comment by k4m4r82** [comment]
Sama om, saya juga lagi nunggu fitur ini rilis di [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js/issues/758) :-D

Klo udah rilis insyaAlloh library WhatsApp NET Client tinggal menyesuaikan

**Comment by rezkiye** [comment]
alhamdulillah. siap saya tunggu updatenya mas rudi. yg versi ini saya coba wa beta stuck di scan qr code.
