### ISSUE TITLE
v2.9.0 (2022-03-12)  ERROR en la version de VB.NET

### ISSUE THREAD

**Issue by soporteLINSA** [WhatsAppNETClient/WhatsAppNETClient2#20]
**Hay un ERROR en la version de VB.NET
NO TRABAJA BIEN** 

![imagen](https://user-images.githubusercontent.com/99940112/158039222-3c7e1896-d4f8-4dab-90f9-9286202c6e70.png)

**La versión de C# NET si trabaja bien....
SI TRABAJA BIEN**
![imagen](https://user-images.githubusercontent.com/99940112/158039374-b4222f19-c1dc-41ce-9843-e535eb35828f.png)

**Comment by WhatsAppNETClient** [comment]
Vale, gracias por la información. Para el ejemplo de código de VB.NET, lo he arreglado

https://github.com/WhatsAppNETClient/WhatsAppNETClient2/commit/dfb90647514cd6147e9b1109270f75d2ddc210da

**Comment by soporteLINSA** [comment]
Hola, Gracias todo trabajando
Saludos desde Costa Rica

**Comment by WhatsAppNETClient** [comment]
Saludos
