### ISSUE TITLE
Link Button

### ISSUE THREAD

**Issue by asyad85** [WhatsAppNETClient/WhatsAppNETClient2#21]
Mas Rudi Kamaruddin semoga sehat selalu, mas mau request kalau boleh terima kasih sekali, kalau gk boleh jg gak apa2 mas. Bisa gk mas buat Link Button kayak contoh image yg saya lampirkan. Terima Kasih mas atas perhatiannya. 

![tombol](https://user-images.githubusercontent.com/68018858/158350454-7c0891c5-600b-4a80-9d06-ae760b8544f8.png)

**Comment by kamarudin2018** [comment]
@asyad85 

Belum support om

**Comment by asyad85** [comment]
siap Mas Rudi
