### ISSUE TITLE
msgArgs = New MsgArgs(message.from, txtPesan.Text, MsgArgsType.Image, tiquetegenerado)

### ISSUE THREAD

**Issue by soporteLINSA** [WhatsAppNETClient/WhatsAppNETClient2#22]
Hola

Consulta como puedo convertir el "message.from" a String
msgArgs = New MsgArgs(message.from, txtPesan.Text, MsgArgsType.Image, tiquetegenerado)

Necesito obtener el número de teléfono en String

saludos

**Comment by WhatsAppNETClient** [comment]
Hola
message.from ya es de tipo cadena

**Comment by soporteLINSA** [comment]
Hola
Si entiendo que es de tipo es String, pero como lo asigno a una variable String...!!!???

Dim contacto as String
contacto = message.from

saludos

**Comment by WhatsAppNETClient** [comment]
yes it is right like this

```
Dim contacto as String
contacto = message.from
```

**Comment by soporteLINSA** [comment]
Cuando agrego esta linea de codigo el Autoreplay deja de funcionar....

![imagen](https://user-images.githubusercontent.com/99940112/159610886-4218c5ca-d491-4cbd-ba86-5ce760c976d6.png)

![imagen](https://user-images.githubusercontent.com/99940112/159610999-779277f9-f93e-4e17-9578-8f40a0abb19e.png)

**Comment by WhatsAppNETClient** [comment]
¿Puede agregar `breakpoint` y hacer `debugging` así, para ver el contenido de la propiedad `from` o `sender` ?

![1](https://user-images.githubusercontent.com/67818764/159617184-f8af644c-3e47-4207-860f-d32b9ca49b53.png)

![2](https://user-images.githubusercontent.com/67818764/159617198-75719551-f446-4108-8f93-90fe3b542876.png)
