### ISSUE TITLE
authentication via json is not supported

### ISSUE THREAD

**Issue by ramosmarthin** [WhatsAppNETClient/WhatsAppNETClient2#23]
please sir

i'm find erorr
![2022-03-24](https://user-images.githubusercontent.com/95949577/159839786-d7dfa893-7d7d-4a02-aeb3-d217a287c821.png)

**Comment by WhatsAppNETClient** [comment]
are you using whatsapp multi-device (beta)?

**Comment by ramosmarthin** [comment]
no sir

**Comment by WhatsAppNETClient** [comment]
can you make a video when the process starts and scan the qrcode?

**Comment by ramosmarthin** [comment]
wait y sir

**Comment by ramosmarthin** [comment]
https://user-images.githubusercontent.com/95949577/159870673-020d6745-b70f-4a8e-8ca2-0058c63fc308.mp4

**Comment by kamarudin2018** [comment]
try uncheck headless checkbox before starting to show chrome browser

**Comment by kamarudin2018** [comment]
and check again whether the whatsapp settings on the iphone are not multi-device

**Comment by WhatsAppNETClient** [comment]
okay, it looks like you activated the beta settings on the phone used to scan the qr code

try checking the multi device checkbox

![md](https://user-images.githubusercontent.com/67818764/159874329-88356555-7f50-4474-bbf2-7b31dfba2385.png)

**Comment by ramosmarthin** [comment]
done sir thanks,
uncheck headless
