### ISSUE TITLE
ChatBot vb.net

### ISSUE THREAD

**Issue by soporteLINSA** [WhatsAppNETClient/WhatsAppNETClient2#24]
Hola
Es posible adaptar el codigo fuente para ser usado como ChatBot
saludos

**Comment by soporteLINSA** [comment]
Hola 
A cual correo me puedo comunicar con usted...
Para consulta de costo de adaptar y desarrollar este proyecto la función de Chatbot en VB.Net 2015 y MySQL Server.
saludos

**Comment by WhatsAppNETClient** [comment]
¿Qué tipo de chatbot quieres construir?

Para contacto, puede contactarme al correo electrónico: rudi-krsoftware@gmail.com

**Comment by soporteLINSA** [comment]
Hola

Lo que se desea es construir un Chatbot Whatsapp con tecnologías JSON,  VB.Net 2015 y  MySQL Server
Sobre el funcionamiento ChatBot.

Requerimientos:
1. CRUD Crear, Actualizar, Eliminar, Leer información en la base de datos.
2. Chatbot CRUD Mensaje de entrada (palabras clave) - Mensaje de salida o respuesta (Mensaje, texto, audio, vídeo o url)
3. Chatbot CRUD debe almacenar todos los numeros de telefono y mensajes recibidos
4. Función de poder limitar la cantidad de respuestas del Chatbot, 1, 2, 3, etc según la necesidad.
5. Función de activación automática por horarios.
6. Código fuente VB.Net 2015 y Script MySQL Server

Email:   informativo@linsa.ed.cr
saludos
