### ISSUE TITLE
kirim URL gagal

### ISSUE THREAD

**Issue by asyad85** [WhatsAppNETClient/WhatsAppNETClient2#25]
mas saya coba kirim pesan dengan type pesan URL dengan format berikut : 

msgArgs = new MsgArgs(kontak, txtPesan.Text, MsgArgsType.Url, "[https](http://wa-net.coding4ever.net/)");

tapi status pengiriman GAGAL, tks mas

**Comment by WhatsAppNETClient** [comment]
Udah nyoba contoh aslinya blm om?
