### ISSUE TITLE
Error: Evaluation failed

### ISSUE THREAD

**Issue by Dieguit0Paz** [WhatsAppNETClient/WhatsAppNETClient2#26]
![image](https://user-images.githubusercontent.com/102425168/160248680-c7c69cfa-f91e-4b15-aba7-963cb6c315a7.png)

Selamat pagi,
Saya mulai mendapatkan detail kesalahan di tangkapan layar setelah berhasil masuk ke whtasapp.
semuanya bekerja dengan baik sampai 5 menit yang lalu

"whatsapp-web.js": {
      "version": "1.16.4",

kesalahan muncul dengan sesi WhatsApp dimulai dan juga ketika yang baru dimulai.
Di browser tidak ada kesalahan yang ditampilkan dan Anda masuk dengan benar

**Comment by WhatsAppNETClient** [comment]
Apakah anda munggunakan whatsapp beta (multi device)?

**Comment by WhatsAppNETClient** [comment]
Setelah saya cek ini merupakan issue dari [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js) jadi kita tunggu saja updatenya

**Comment by Dieguit0Paz** [comment]
Por las dudas a alguien mas le pase y le sirva, en mi caso se solucionó de la siguiente forma:
"whatsapp-web.js": "versión": "1.16.4",

Dentro de la carpeta `Masivos WhatsApp CUO\bin\Debug\WhatsAppNETAPINodeJs\node_modules\whatsapp-web.js\src\util`
esta el archivo `Injected.js`
En la fila 43  tenemos este comando `window.Store.getProfilePicFull = window.mR.findModule('getProfilePicFull')[0].getProfilePicFull` lo comenté con la doble barra  `//`
y debajo añadí `window.Store.getProfilePicFull = window.mR.findModule('getProfilePic')[0].getProfilePic;`
quedando de la siguiente forma

![image](https://user-images.githubusercontent.com/102425168/160391363-2c9c3035-3fc2-4323-85fb-ff33a2b8a0ef.png)


Guardé el archivo y quedo nuevamente funcionando ok.

Saludos
