### ISSUE TITLE
Es posible limitar el autoreplay

### ISSUE THREAD

**Issue by soporteLINSA** [WhatsAppNETClient/WhatsAppNETClient2#27]
Es posible limitar el autoreplay a 1 una sola autorespuesta para cada numero telefonico

saludos

**Comment by WhatsAppNETClient** [comment]
Perdon no entiendo muy bien la pregunta

**Comment by soporteLINSA** [comment]
Hola

Como se puede hacer para que la aplicación de autorespuesta envie una 1 sola respuesta por mensaje recibido...

1 mensaje de respuesta unicamente por cada mensaje de entrada....

saludos

**Comment by WhatsAppNETClient** [comment]
Hola

Sí, puede, por lo que todos los mensajes entrantes se guardan en la base de datos, por ejemplo, utilizando la tabla de la bandeja de entrada, por lo que cada mensaje entrante tiene su número de teléfono en comparación con los datos que ya están en la tabla de la bandeja de entrada.

**Comment by soporteLINSA** [comment]
Hola

Como se puede hacer para que la aplicación de autorespuesta envie una 1 sola respuesta por mensaje de telefono recibido, sin utlizar una base de datos....

1 mensaje de respuesta unicamente por cada mensaje de entrada....solo responder una unica vez por cada mensaje de numero de telefono recibido....

Que estoy haciendo...
En el **listbox** estoy tratando de hacer una busqueda del numero de telefono como cadena, si es **"verdadero"** no contestar el automensaje....No logro que funcione....
saludos

**Comment by WhatsAppNETClient** [comment]
@soporteLINSA 

Puede utilizar colecciones como listas.

Ejemplo:

```
Dim contacts As New List(Of String)

contacts.Add("081281562912")
contacts.Add("081381669313")
contacts.Add("081481764914")
contacts.Add("081581869955")

Dim findPhonenumber As String = "081481764914"
Dim count = contacts.Where(Function(f) f = findPhonenumber).Count()
If (count > 0) Then
	Console.WriteLine("Phone Number exist")

Else
	Console.WriteLine("Phone Number not exist")
End If
```
