### ISSUE TITLE
Tidak dapat melakukan autentikasi seletah update app WhatsApp

### ISSUE THREAD

**Issue by MrPentiumII** [WhatsAppNETClient/WhatsAppNETClient2#28]
Error : Evaluation failed: TypeError : Cannot read properties of undefined (reading 'getProfilePicFull'))
Untuk versi App WhatsApp sebelum nya tidak ada masalah, tetapi setelah saya melakukan pembaruan  whatsapp di playstore,
muncul pesan tersebut saat autentikasi

**Comment by WhatsAppNETClient** [comment]
@MrPentiumII 

Lakukan update [whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js/), berikut langkah-langkahnya:

1. Buka command prompt
2. Pindah ke folder WhatsAppNETAPINodeJs
3. Ketik perintah: `npm update whatsapp-web.js`

![wa](https://user-images.githubusercontent.com/67818764/160715912-6f250418-a27a-4b80-85e2-b572c089b603.png)

**Comment by MrPentiumII** [comment]
Oke terimakasih bg,masalah nya sudah teratasi
