### ISSUE TITLE
Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.

### ISSUE THREAD

**Issue by asyad85** [WhatsAppNETClient/WhatsAppNETClient2#29]
saya setelah scan qr code nya muncul begini y mas : Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.

**Comment by WhatsAppNETClient** [comment]
Coba baca2x dulu om, sebelum buka issue yg baru

cek issue [authentication via json is not supported](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/issues/23)

**Comment by asyad85** [comment]
iya mas maaf, sudah ketemu penyebabnya, trima kasih atensinya mas 👍

**Comment by asyad85** [comment]
Maaf mas tanya lagi, bisa gak whatsapp web di Embedded ke Form dari session WhatsAppNETClient, makasih mas 🥇

**Comment by WhatsAppNETClient** [comment]
Kenapa harus Embedded om? Kebanyakan orang malah enggak mau klo whatsapp webnya ditampilkan

**Comment by asyad85** [comment]
Maksud nya biar WhatsApp Web nya juga bisa diakses dalam satu Aplikasi WhatsAppNETClient ini mas

**Comment by WhatsAppNETClient** [comment]
Coba aja om pake [CEFSharp](https://cefsharp.github.io/) mana tau bisa diembedkan

**Comment by asyad85** [comment]
iya mas ini lg coba2 pake libs CEFSharp, btw trima kasih banyak mas atas atensi nya
