### ISSUE TITLE
Multiple Session for Multiple Number

### ISSUE THREAD

**Issue by radiaku** [WhatsAppNETClient/WhatsAppNETClient2#31]
Halo, Pak. Library nya support untuk multiple session untuk multiple number ( whatapps ), tidak ya?
Saya lihat di  'WhatsAppNETAPINodeJs' terdapat folder session tersendiri dan di file .env ada deklarasinya. 

Bisa di kasih preferensi atau pengarahannya.

Terimakasih.

**Comment by WhatsAppNETClient** [comment]
Coba petunjuknya di http://wa-net.coding4ever.net/

**Comment by radiaku** [comment]
Thanks Pak. Demonya membantu memahami alurnya.

**Comment by WhatsAppNETClient** [comment]
> Thanks Pak. Demonya membantu memahami alurnya.

Sama-sama, sebagai tambahan informasi:

Untuk yang non MD, menggunakan file `json` yang tersimpan di folder `session`, sedangkan yang MD akan membuat folder `.wwebjs_auth`

**Comment by khoirulh1610** [comment]
Maaf pak, saya juga mau tanya nih, untuk session-name apakah bisa di setup dari sisi c#/vb nya. bukan dari file .env nya. karena butuh custom sessionnya

**Comment by WhatsAppNETClient** [comment]
@khoirulh1610 

bisa om, utk sessionnya bisa dilewatkan via constructor pada saat membuat objek dari wa net, untuk contohnya bisa dilihat di[sini](https://github.com/WhatsAppNETClient/WhatsAppNETClientMultiAccount/blob/5233b1bb5b9fc9adba356f153f97ebbab80e12c5/src/DemoWhatsAppNETAPIMultiAccountVBNET/FrmMain.vb#L110).
