### ISSUE TITLE
Whatsapp Can't Send Message and AutoReply

### ISSUE THREAD

**Issue by Koichiro12** [WhatsAppNETClient/WhatsAppNETClient2#32]
Selamat Pagi,Nama saya Choirul, Saya ingin mengajukan laporan bug yang saya temukan saat proses develop menggunakan library yang anda kembangkan.

BUG yang saya temukan

1. Kemarin saya mencoba mendevelop beberapa aplikasi berbeda menggunakan library yang anda kembangkan, dan itu semua berjalan normal. hari ini ketika saya mencoba lagi. saya menemukan error seperti ini

![image](https://user-images.githubusercontent.com/49182827/164579005-6cb15dd4-2e43-4684-bff3-cf0b78c10fc1.png)

Error tersebut membuat saya tidak dapat mengirim pesan ataupun AutoReply. Saya kira ini kode saya yang bermasalah. dan saya putuskan menggunakan DemoWhatsappApi yang disediakan dan hasil nya sama, saya tidak dapat mengirim reply atau mengirim pesan.

![image](https://user-images.githubusercontent.com/49182827/164579165-49310934-75b3-4765-b9f9-721557d7de36.png)

![image](https://user-images.githubusercontent.com/49182827/164579212-6b3690f0-f72a-4687-a14e-3811c825be3e.png)

2. Saat saya mencoba update WhatsApp yang berada di web. Chrome tiba" Force close dan modul terhenti.

![image](https://user-images.githubusercontent.com/49182827/164579498-490ebdd8-a164-40f5-bbe3-0445137d52f8.png)

**Comment by WhatsAppNETClient** [comment]
@Koichiro12 

Update library [whatsapp-web.jesnya](https://github.com/pedroslopez/whatsapp-web.js/) om, caranya:

- Buka command prompt trus masuk ke folder WhatsApp NET API NodeJs
- Kemudian ketik perintah: `npm update whatsapp-web.js`
- Selesai

**Comment by Koichiro12** [comment]
Baik terimkasih, Sudah Berjalan Normal Kembali
