### ISSUE TITLE
I Got Snap After Run Modul 24 Hours

### ISSUE THREAD

**Issue by Koichiro12** [WhatsAppNETClient/WhatsAppNETClient2#33]
Selamat Pagi, Saya Mendapat Beberapa Kali Aw,Snap pada chromium saat modul saya berjalan sekitar 20 jam sampai 1 hari. Beberapa kali juga saat saya baru menjalankan modul juga mendapat kendala tersebut. whatsapp-web.js juga sudah di update dan cookie yang ada di chromium sudah di hapus ,untuk mengatasi kendala apa yang harus saya lakukan ?.

![image](https://user-images.githubusercontent.com/49182827/165420856-0968ea1a-cad2-4f2a-a1fb-1ff78752d115.png)

**Comment by WhatsAppNETClient** [comment]
@Koichiro12 

1. whatsapp-web.js sudah menggunakan versi 1.16.6?
2. ini jalannya di wa MD atau bukan?

**Comment by WhatsAppNETClient** [comment]
@Koichiro12 

Coba langkah-langkah ini om:

1. Dari link device, di logout dulu session yg aktif
2. Hapus folder .wwebjs_auth yg ada di folder wa node js
3. Konek ulang

**Comment by Koichiro12** [comment]
@WhatsAppNETClient 

- whatsapp-web.js sudah menggunakan versi 1.16.6
- tidak jalan di wa MD

**Comment by Koichiro12** [comment]
@WhatsAppNETClient

Siap nanti kita coba langkah" Tersebut.

**Comment by Koichiro12** [comment]
Selamat sore.... Beberapa langkah yang sudah di cantumkan sudah saya lakukan, Hasilnya yang di dapat tetap sama ... Kadang mengalami snap. Mohon solusinya🙏🙏

**Comment by Koichiro12** [comment]
> Selamat sore.... Beberapa langkah yang sudah di cantumkan sudah saya lakukan, Hasilnya yang di dapat tetap sama ... Kadang mengalami snap. Mohon solusinya🙏🙏
