### ISSUE TITLE
I Got Snap Again

### ISSUE THREAD

**Issue by Koichiro12** [WhatsAppNETClient/WhatsAppNETClient2#35]
Selamat sore.... Beberapa langkah langkah pada Issue #33  yang sudah di cantumkan sudah saya lakukan, Hasilnya yang di dapat tetap sama ... Kadang mengalami snap. Mohon solusinya🙏🙏.

**Comment by WhatsAppNETClient** [comment]
Setelah menjalankan langkah-langkah ini

- Dari menu link device (wa mobile), di logout dulu session yg aktif
- Hapus folder .wwebjs_auth yg ada di folder wa node js
- Konek ulang
- Set property Headless = true (no window)
