### ISSUE TITLE
Dukungan untuk versi .NET selain .NET Framework

### ISSUE THREAD

**Issue by EmiyaSyahriel** [WhatsAppNETClient/WhatsAppNETClient2#38]
Halo, saya ingin tahu apakah kedepannya ada rencana untuk modul NuGet dari WhatsAppNETAPI agar mendukung versi .NET selain .NET Framework seperti .NET Standard, .NET Core atau .NET 5.0/6.0+, 

Ya~ berhubung .NET Framework khusus untuk Windows (dan secara parsial dengan Mono) jadi mungkin akan lebih banyak yang pakai library ini jika dukungan ke seri .NET yang lain juga dibuat karena lebih banyak opsi platform disana.

Saya sedang mempertimbangkan untuk memakai library ini untuk aplikasi lintas-platform dengan .NET 5.0, soalnya ketika saya mencoba memakai paket NuGet di project .NET 5.0, NuGet restore selalu gagal karena sepertinya beberapa dependensi yang dipakai di library ini gak cocok dengan versi yang lebih baru di .NET 5.0.

**Comment by WhatsAppNETClient** [comment]
Menarik, tapi ya memang butuh banyak penyesuaian di library .NET dan script di NodeJSnya
