### ISSUE TITLE
Error : Authenticating via JSON session not support

### ISSUE THREAD

**Issue by suhartoschn** [WhatsAppNETClient/WhatsAppNETClient2#39]
after scan QR by Phone, muncul errorr "Error : Authenticationg via JSON session not support"
Bisa di bantu solusi tersebut 
![error](https://user-images.githubusercontent.com/107026193/172314650-4b075019-3900-4b0f-8fba-a4981009cd3a.jpg)

**Comment by WhatsAppNETClient** [comment]
Sebelum membuat issue, cek dulu issue2x yg sudah ada om, seperti [ini](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/issues/23)

**Comment by suhartoschn** [comment]
![uncheck](https://user-images.githubusercontent.com/107026193/172325368-33ded33d-e513-42f9-b793-dfc19ef2a36e.jpg)

setelah uncheck ,masih belum bisa ke aplikasi main
mhn di bantu

**Comment by suhartoschn** [comment]
![Chrome_wa_web_inside_app](https://user-images.githubusercontent.com/107026193/172325878-094bc03c-b455-4c39-8518-30ec26278535.jpg)

**Comment by WhatsAppNETClient** [comment]
Pilihan *multi devicenya* om dicheck, kan om pake WA yang udah multi device kan?

**Comment by WhatsAppNETClient** [comment]
Kan di [ISSUE](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/issues/23#issuecomment-1077363446) ini udah jelas  solusinya
