### ISSUE TITLE
List Contact & group_member Tidak muncul

### ISSUE THREAD

**Issue by suhartoschn** [WhatsAppNETClient/WhatsAppNETClient2#40]
Dear sir,
mohon di bantu utk list contact & group tidak muncul
-status koneksi masih aktif (android)
- send bisa
![list_contact](https://user-images.githubusercontent.com/107026193/172823356-0f887c65-77f2-4359-847f-762a79cf4272.jpg)

**Comment by WhatsAppNETClient** [comment]
Update versi [whatsapp-web.js](https://www.npmjs.com/package/whatsapp-web.js)
