### ISSUE TITLE
Gagal Scan Barcode

### ISSUE THREAD

**Issue by azhyev** [WhatsAppNETClient/WhatsAppNETClient2#41]
Terimakasih sebelumnya sudah sharing projeknya.
Saya ada error waktu scan barcode :  Authenticating via JSON support is not supported.
Mohon bantuannya.

![image](https://user-images.githubusercontent.com/107377869/173266663-9d1d85ba-8eef-4183-a4a4-a83fe17ddfda.png)

**Comment by WhatsAppNETClient** [comment]
Sebelum create issue yang baru, biasakan cek issue yang sudah [CLOSE](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/issues?q=is%3Aissue+is%3Aclosed)

**Comment by azhyev** [comment]
Maaf ternyata sudah ditanyakan. Terimakasih.
