### ISSUE TITLE
Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.

### ISSUE THREAD

**Issue by sajithnechiparambil** [WhatsAppNETClient/WhatsAppNETClient2#42]
Error generated after scanning qr-code -> Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.

**Comment by edywdono** [comment]
same problem

**Comment by WhatsAppNETClient** [comment]
Closed [here](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/issues/39)
