### ISSUE TITLE
Events not firing

### ISSUE THREAD

**Issue by diegoaraujolima** [WhatsAppNETClient/WhatsAppNETClient2#43]
Hello. I'm using your desktop demo application as a base to build mine in WPF. I followed the same example as yours and after calling the Connect() method it is not triggering any events (StartUp, ScanMe, and etc).

Is there any way I can debug to find out what might be going on?

**Comment by WhatsAppNETClient** [comment]
Sorry I don't have a demo version of wfp

**Comment by diegoaraujolima** [comment]
Where are the sorce code from WhatsAppNETAPI nuget package?

 

De: WhatsAppNETClient ***@***.***> 
Enviada em: quarta-feira, 22 de junho de 2022 00:48
Para: WhatsAppNETClient/WhatsAppNETClient2 ***@***.***>
Cc: Diego ***@***.***>; Author ***@***.***>
Assunto: Re: [WhatsAppNETClient/WhatsAppNETClient2] Events not firing (Issue #43)

 

Sorry I don't have a demo version of wfp
