### ISSUE TITLE
Kirim pesan lebih lambat sampai tidak terkirim

### ISSUE THREAD

**Issue by Koichiro12** [WhatsAppNETClient/WhatsAppNETClient2#45]
Selamat pagi, Hari ini library mengirim pesan lebih lambat bahkan pesan tidak terkirim. Apakah ada update atau penambahan fitur ?

**Comment by WhatsAppNETClient** [comment]
@Koichiro12 

[whatsapp-web.js](https://github.com/pedroslopez/whatsapp-web.js/) pake versi brp om?

**Comment by Koichiro12** [comment]
untuk saat ini versi dipakai versi lama,Untuk Rekomendasi nya pakai versi berapa ?

**Comment by WhatsAppNETClient** [comment]
Yg terbaru versi 1.17.0, coba diupdate dulu

**Comment by Koichiro12** [comment]
Baik, apakah harus update node JS juga ?

**Comment by WhatsAppNETClient** [comment]
Coba update file `Client.js` yang ada di folder `WhatsAppNETAPINodeJs\node_modules\whatsapp-web.js\src`

trus edit kode utk method `getNumberId` seperti berikut:

```
async getNumberId(number) {
	if (!number.endsWith('@c.us')) {
		number += '@c.us';
	}

	return await this.pupPage.evaluate(async number => {
		// const result = await window.Store.QueryExist(number);
		const wid = window.Store.WidFactory.createWid(number);
		const result = await window.Store.QueryExist(wid);
		
		if (!result || result.wid === undefined) return null;
		return result.wid;
	}, number);
}
```

**Comment by Dieguit0Paz** [comment]
> Archivo de actualización de Coba `Client.js`yang ada di carpeta`WhatsAppNETAPINodeJs\node_modules\whatsapp-web.js\src`
> 
> trus edit kode utk método `getNumberId`seperti berikut:
> 
> ```
> async getNumberId(number) {
> 	if (!number.endsWith('@c.us')) {
> 		number += '@c.us';
> 	}
> 
> 	return await this.pupPage.evaluate(async number => {
> 		// const result = await window.Store.QueryExist(number);
> 		const wid = window.Store.WidFactory.createWid(number);
> 		const result = await window.Store.QueryExist(wid);
> 		
> 		if (!result || result.wid === undefined) return null;
> 		return result.wid;
> 	}, number);
> }
> ```

Muchas Gracias, con este cambio se logra solucionar los errores de envío.
Saludos Ídolo.

**Comment by WhatsAppNETClient** [comment]
> > Archivo de actualización de Coba `Client.js`yang ada di carpeta`WhatsAppNETAPINodeJs\node_modules\whatsapp-web.js\src`
> > trus edit kode utk método `getNumberId`seperti berikut:
> > ```
> > async getNumberId(number) {
> > 	if (!number.endsWith('@c.us')) {
> > 		number += '@c.us';
> > 	}
> > 
> > 	return await this.pupPage.evaluate(async number => {
> > 		// const result = await window.Store.QueryExist(number);
> > 		const wid = window.Store.WidFactory.createWid(number);
> > 		const result = await window.Store.QueryExist(wid);
> > 		
> > 		if (!result || result.wid === undefined) return null;
> > 		return result.wid;
> > 	}, number);
> > }
> > ```
> 
> Muchas Gracias, con este cambio se logra solucionar los errores de envío. Saludos Ídolo.

de nada
