### ISSUE TITLE
Message.id

### ISSUE THREAD

**Issue by IKHWAN619** [WhatsAppNETClient/WhatsAppNETClient2#46]
Selamat malam assalamualaikum wr.wb Pak rudi
bagaimana untuk mendapatkan messageid dari pengirim dan penerima ya Pak ?
jadi pada saat saya mau ngebalas WABot otomatis messageid saya dan pesan yg saya balas akan keluar di wabot nya.
trimakasih Bapak

**Comment by WhatsAppNETClient** [comment]
MessageIdnya bisa di dapat dari event [OnReceiveMessageStatus](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/blob/34092d60abc80e1d9eee87cf0f1c222c01295853/src/DemoWhatsAppNETAPICSharp/FrmMain.cs#L580)
