### ISSUE TITLE
Error Scan Qr

### ISSUE THREAD

**Issue by ridwan-aswan** [WhatsAppNETClient/WhatsAppNETClient2#47]
Pak saya tidak bisa masuk setelah scan qr.
saya sudah menginstall semua yg di perlukan pak.

![Untitled](https://user-images.githubusercontent.com/56959334/181186725-61a9368e-dae3-4b28-a309-a370e93c0905.png)

**Comment by WhatsAppNETClient** [comment]
Harusnya cek issue yg closed dulu, sebelum buat yag baru

https://github.com/WhatsAppNETClient/WhatsAppNETClient2/issues?q=is%3Aissue+is%3Aclosed

Udah banyak yg nanyain
