### ISSUE TITLE
Status hanya "WAIT"

### ISSUE THREAD

**Issue by ibnu87** [WhatsAppNETClient/WhatsAppNETClient2#48]
mohon bantuannya...
Saat file exe di jalankan hanya menampilkan "WAIT" tanpa adanya Initialize atau scan code, 
terimakasih sebelumya

**Comment by andrie1s** [comment]
idem, juga terjadi seperti ini

**Comment by WhatsAppNETClient** [comment]
coba dikirimkan gambarnya sebelum dan sesudah mengklik tombol start

**Comment by WhatsAppNETClient** [comment]
Coba update versi whatsapp-web.js yg ada di folder WhatsAppNETAPINodeJs
