### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by KINGMASTERAPP** [WhatsAppNETClient/WhatsAppNETClient2#49]
Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.

Saat menelepon dan memindai QR
Apa solusi untuk masalah ini?

**Comment by WhatsAppNETClient** [comment]
@KINGMASTERAPP 

Sebelum create issue baru, sebaiknya cek dulu issue2x yg statunya udah close

Issue in isudah tersolusikan di [sini](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/issues/39)
