### ISSUE TITLE
Gagal Setelah App Exit

### ISSUE THREAD

**Issue by lordahmad12** [WhatsAppNETClient/WhatsAppNETClient2#50]
Salam sehat pak,mau tanya..saya pakai sample source bawaan,pertama buka app normal,koneksi juga normal.
Tapi yang jadi kendala,ketika applikasi diclose **_tanpa logout_** dan ketika aplikasi dibuka kembali, aplikasi selalu gagal kirim pesan.
Padahal sebelum update whatsapp terbaru, semua normal
<img width="956" alt="lapor" src="https://user-images.githubusercontent.com/116192625/196904796-e6088c6f-1659-41d8-8dab-b95d36a4e9c8.png">

**Comment by WhatsAppNETClient** [comment]
Coba update versi whatsapp-web.js yg ada di folder WhatsAppNETAPINodeJs

**Comment by lordahmad12** [comment]
Thx gan.
