### ISSUE TITLE
Setelah Scan, Tidak ada respon

### ISSUE THREAD

**Issue by Koichiro12** [WhatsAppNETClient/WhatsAppNETClient2#51]
Selamat pagi.... ini saya mendapat kendala setelah scan tidak muncul apa" atau tidak response, dan session yang biasa nya tersimpan otomatis tidak ada. Apa ada kendala atau update untuk library ini ?

**Comment by Koichiro12** [comment]
keadaan chromium ke close jika headless tidak di centang

**Comment by WhatsAppNETClient** [comment]
Coba update versi whatsapp-web.js yg ada di folder WhatsAppNETAPINodeJs

**Comment by Koichiro12** [comment]
beberapa sudah saya update, setelah update muncul issue #30 tetapi yang undefined default seperti pada gambar berikut
![image](https://user-images.githubusercontent.com/49182827/201450785-975f4b1b-2c99-482e-bd1d-45715a2396ab.png)

**Comment by cipeu** [comment]
Saya juga mengalami hal yang sama
Setelah scan muncul error Evaluation filed

**Comment by WhatsAppNETClient** [comment]
Langkah-langkah update:

1. Pastikan whatsapp-web.js sudah update ke versi *1.18.3*
2. Copykan isi file patch.zip ke folder WhatsAppNETAPINodeJs\node_modules\whatsapp-web.js\src

[patch.zip](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/files/10073223/patch.zip)
