### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by djnonk** [WhatsAppNETClient/WhatsAppNETClient2#53]
tumben erronya agak lama mas.. di update biasanya langsung bs ni dah 3 hari error:can not read property of undefined(reading 'default')

**Comment by WhatsAppNETClient** [comment]
Update library [whatsapp-web.js](https://www.npmjs.com/package/whatsapp-web.js)nya om

**Comment by djnonk** [comment]
udah bisa mas makasih..
