### ISSUE TITLE
tiba-tiba tidak bisa kirim pesan

### ISSUE THREAD

**Issue by WendyGunawanLiang** [WhatsAppNETClient/WhatsAppNETClient2#54]
Hi, semenjak kemarin malam jam 12, aplikasi demo WhatsAppNetClient tidk bisa kirim pesan sama sekali, status kirim selalu gagal, kenapa yah? saya sudah update whatsapp-web.js namun tidak ada hasilnya..folder .wwebjs_auth juga sudah saya hapus namun tidak ada hasil..makasih sebelumnya

**Comment by djnonk** [comment]
sama mas..mungkin wa officialnya update dan masih di uik2 sama kang kamarudin. di tunggu aja hehe..

**Comment by WhatsAppNETClient** [comment]
Langkah-langkah update:

1. Pastikan whatsapp-web.js sudah update ke versi *1.18.3*
2. Copykan isi file patch.zip ke folder WhatsAppNETAPINodeJs\node_modules\whatsapp-web.js\src

[patch.zip](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/files/10073215/patch.zip)

**Comment by cipeu** [comment]
Halo suhu
Masih belum send.

Sudah update whatsapp-web.js ke versi terbaru
Udah copy patch.zip

Masih belum berhasil kirim WA.

**Comment by PossiSoftware** [comment]
Seleymun Aleykum;
Bisa juga menambahkan gambar di pesan dengan tipe  'Button'
Mengirim pesan dengan tipe 'list'
Fitur yang saya tulis sudah lama tidak digunakan. Apakah ada pembaruan baru yang tersedia? Apa yang perlu kita lakukan? Terima kasih.
