### ISSUE TITLE
Kirim pesan list tidak terkirim

### ISSUE THREAD

**Issue by WendyGunawanLiang** [WhatsAppNETClient/WhatsAppNETClient2#55]
Saat saya coba pakai opsi pesan kirim pesan list, status kirim berhasil, namun pesan list tidak sampai ke penerima, namun jika saat cek wa pengirim (via hp) pesannya listnya mmg ada, namun dari sisi penerima tidak masuk, kenapa yah?

**Comment by WhatsAppNETClient** [comment]
@WendyGunawanLiang 

Dulu sempat support ngirim list dan button, tapi setelah ada perubahan di WA web, perlu ada penyesuaian lagi. Untuk progress issuenya bisa cek di [sini](https://github.com/pedroslopez/whatsapp-web.js/pull/1636).

**Comment by WhatsAppNETClient** [comment]
Klo om @WendyGunawanLiang, pengen nyoba fitur ngirim list dan button caranya gampang:

1. Buka console trus masuk ke folder `WhatsAppNETAPINodeJs`
2. Trus jalankan perintah: npm i github:pedroslopez/whatsapp-web.js#fix-buttons-list
3. Selesai

**Comment by WendyGunawanLiang** [comment]
ok untuk list dan button biasa sudah berfungsi, kecuali button dengan gambar masih tidak berfungsi

**Comment by WhatsAppNETClient** [comment]
Di versi terbaru sudah bisa menggunakan kembali fitur ini om
