### ISSUE TITLE
Button and list messages

### ISSUE THREAD

**Issue by MahmoudAfifyM** [WhatsAppNETClient/WhatsAppNETClient2#56]
i can't send inteactive button message or list and icand sign in as standerd account to use it it's only multi device
and how can i send multi image in one message

**Comment by MahmoudAfifyM** [comment]
i found that npm i github:pedroslopez/whatsapp-web.js#fix-buttons-list but i have another problem
when i send list and i got reply from this list  it's stop working so i can't recieve or send any more

**Comment by WhatsAppNETClient** [comment]
In the latest version, this feature can be used again
