### ISSUE TITLE
menggunakan tools ini sebagai background process (windows services)

### ISSUE THREAD

**Issue by WendyGunawanLiang** [WhatsAppNETClient/WhatsAppNETClient2#57]
apakah saya bisa menggunakan tools ini sebagai windows services? 
saya coba mengimplementasikan sebagai windows service nya tapi sepertinya tidak berjalan..saat connect tidak terjadi apa2. apakah memang tidak support sebagai background services? 

apakah harus ada interaksi ke UI baru tools ini berjalan? soalnya saat pertama kali scan barcode di UI, kemudian start servicenya, dia bisa bisa bekerja normal, namun kalau sudah close UI nya (padahal service berjalan terus di backend thread). prosesnya berhenti..dan saaat start service lagi tidak otomatis connect..jadi harus masuk ke UI untuk scan barcode lagi (walaupun tidak scan lagi karena otomatis ambil session sebelumnya) supaya ke connect.

mohon pencerahannya

**Comment by WhatsAppNETClient** [comment]
Belum nyoba, mungkin solusi sederhananya hasil qrcodenya di simpan di folder local om, itu yg di scan
