### ISSUE TITLE
Histori Chat

### ISSUE THREAD

**Issue by asyad85** [WhatsAppNETClient/WhatsAppNETClient2#6]
Mas Rudi, adakah fitur untuk mengambil histori chat dari whatsapp? tampilan sama seperti yang ada pada whatsapp, tks

**Comment by WhatsAppNETClient** [comment]
@asyad85, insyaAlloh bisa saya sediakan fiturnya

**Comment by asyad85** [comment]
> 
> 
> @asyad85, insyaAlloh bisa saya sediakan fiturnya

mantap mas rudi, semoga menjadi amal jariyah, aamiin

**Comment by WhatsAppNETClient** [comment]
aamiin
