### ISSUE TITLE
Kirim File dengan pesan

### ISSUE THREAD

**Issue by WendyGunawanLiang** [WhatsAppNETClient/WhatsAppNETClient2#60]
Bagaimana cara kirim file dengan pesan? kalau saya pakai function New MsgArgs(oMessageTo, oMessage, MsgArgsType.File, oAttachment) cuman file yang terkirim tapi pesan/messagenya hilang dan ke replace dengan nama filenya..

mohon pencerahannya

**Comment by WhatsAppNETClient** [comment]
Di versi terbaru sudah bisa untuk fitur ini om
