### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by mrjay59** [WhatsAppNETClient/WhatsAppNETClient2#64]
![image](https://user-images.githubusercontent.com/66785677/223636987-cef623c5-5e62-4976-9e79-d307fca3e73f.png)

node js sudah versi 16 
apa ada yang kurang

**Comment by WhatsAppNETClient** [comment]
Coba ganti versi link-preview-js di file https://github.com/WhatsAppNETClient/WhatsAppNETAPINodeJs2/blob/master/package.json

menjadi "link-preview-js": "^3.0.4"

**Comment by KautsarCiptaWiharja** [comment]
di dalam package.json delete 
  "@whiskeysockets/baileys": "^6.5.0",   <<< DELETE
      "sharp": "^0.30.4",    <<< DELETE
lalu coba kembali
npm install
npm install pino
npm install @whiskeysockets/baileys
