### ISSUE TITLE
Pesan reply : tidak muncul isi, hanya message sebelumnya

### ISSUE THREAD

**Issue by cipeu** [WhatsAppNETClient/WhatsAppNETClient2#65]
Jika menerima pesan berupa reply hanya masuk yang reply message sebelumnya.
Isi message nya malah tidak masuk.

**Comment by Dieguit0Paz** [comment]
Hal yang sama terjadi pada saya di acara "OnReceiveMessageStatusHandler" ketika saya mengirim pesan dengan gambar. Di versi sebelumnya, teks tiba sebagai properti dari variabel Status. sekarang tiba nol

**Comment by WhatsAppNETClient** [comment]
Sudah diperbaiki, silahkan update https://github.com/WhatsAppNETClient/WhatsAppNETAPINodeJs2
