### ISSUE TITLE
Membantu dengan VerifyWANumber(IList<string> contacts)

### ISSUE THREAD

**Issue by Dieguit0Paz** [WhatsAppNETClient/WhatsAppNETClient2#66]
selamat pagi, dapatkah seseorang memberikan contoh di vb.net tentang penggunaan metode VerifyWANumber(IList<string> contacts)
Dari sudah terima kasih banyak

**Comment by WhatsAppNETClient** [comment]
Contohnya sudah ada di https://github.com/WhatsAppNETClient/WhatsAppNETClient2/blob/07667d76b711f994afdf807c4c9b5b7eb8cec5f0/src/DemoWhatsAppNETAPIVBNET/FrmMain.vb#L1094
