### ISSUE TITLE
Buttons and List Send

### ISSUE THREAD

**Issue by PossiSoftware** [WhatsAppNETClient/WhatsAppNETClient2#68]
Selamun aleykum. Although it worked very stable until the previous day, today the buttons and lists do not reach the other side. Thanks in advance for your help.

**Comment by WhatsAppNETClient** [comment]
Waalaikumussalam

Yes, for now the button and list messages cannot be used after WhatsApp has updated.

I'm also waiting for the latest development info from [Baileys - Typescript/Javascript WhatsApp Web API](https://github.com/adiwajshing/Baileys/issues)

**Comment by PossiSoftware** [comment]
Thanks. I would be grateful if you let me know when there is a new development.

**Comment by WhatsAppNETClient** [comment]
Message button and list are deprecated
