### ISSUE TITLE
Stuck di proses Authenticate

### ISSUE THREAD

**Issue by nyugithub-dev** [WhatsAppNETClient/WhatsAppNETClient2#7]
Salam, pak. Maaf saya mau tanya, saya sudah coba jalankan project ini, sudah berhasil sampai scan qr code tapi selalu stuck di proses Authenticate, jadi tidak bisa masuk ke proses selanjutnya seperti kirim message, etc. Saya sudah pastikan internet lancar dan whatsapp berjalan baik di hp, Node js juga sudah terinstall dan start. Pokoknya sudah seperti langkah-langkah di http://wa-net.coding4ever.net/. Mohon bantuannya pak. Terima kasih banyak.

**Comment by WhatsAppNETClient** [comment]
@nyugithub-dev, coba hapus folder **session** yg ada di folder WhatsAppNETAPI NodeJs mba

**Comment by rusdyrip** [comment]
halo saya juga mengalami masalah seperti ini.apakah ada solusi lain selain menghapus folder session?
