### ISSUE TITLE
Error With Contact List and Buttons on  Baileys API

### ISSUE THREAD

**Issue by acid75** [WhatsAppNETClient/WhatsAppNETClient2#70]
you cant use the Contacts List anymore if you use it auto Disconnect and you have to close it and re open it to send messages again

with the buttons and the Menu its the same 

another error i found is if you send a difusion message with the list you can only send 15 messages after they block you 24 hours
i wonder if there is a documentation for that or the cuantity of msg you can send in X time becase im using wait between msg of 10000ms

**Comment by WhatsAppNETClient** [comment]
Message button and list are deprecated
