### ISSUE TITLE
tidak bisa koneksi ke wa

### ISSUE THREAD

**Issue by argostek** [WhatsAppNETClient/WhatsAppNETClient2#71]
saat klik start nyangkut di intialize

**Comment by WhatsAppNETClient** [comment]
Perlu update om:
1.  Download ulang atau clone project https://github.com/WhatsAppNETClient/WhatsAppNETAPINodeJs2
2. Buka command prompt trus ketik: npm install

**Comment by argostek** [comment]
assalamualaikum mas,
sudah bisa mas,
td ada error saya update node js nya dan bisa
