### ISSUE TITLE
Kirim Pesan List status berhasil tetapi pesan tidak masuk

### ISSUE THREAD

**Issue by IKHWAN619** [WhatsAppNETClient/WhatsAppNETClient2#73]
Assalamualaikum bapak. . .
kenapa yaa saat saya mau kirim pesan list kok pesan tidak sampai ke WA penerima. . .
padahal status pada pesan kluar berhasil. . .
mohon pencerahannya suhu. .. 
trimakasih

**Comment by WhatsAppNETClient** [comment]
Waalaikumussalam

Untuk pesan list dan button sudah enggak di support om

**Comment by IKHWAN619** [comment]
oke Pak terimakasih infonya
