### ISSUE TITLE
error pada saat form scan barcode "TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: base64url"

### ISSUE THREAD

**Issue by xxxmarkoxxx** [WhatsAppNETClient/WhatsAppNETClient2#74]
mohon bantuanya gan
ane nemu error "TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: base64url" 
padahal sudah ikutin langkah2 dari awal
untuk versi node jg sudah 14.16.0
koneksi ke mysql sudah benar (.env)
mohon solusinya gan
terima kasih
![error](https://github.com/WhatsAppNETClient/WhatsAppNETClient2/assets/45991802/a548b778-a4f1-4abc-bb68-08314fdfc64b)

**Comment by WhatsAppNETClient** [comment]
Untuk project WhatsAppNETAPINodeJs menggunakan project yg [ini](https://github.com/WhatsAppNETClient/WhatsAppNETAPINodeJs2) om 

Trus utk versi nodenya update ke versi v16.18.x
