### ISSUE TITLE
Stuck pada proses wait

### ISSUE THREAD

**Issue by gaul56** [WhatsAppNETClient/WhatsAppNETClient2#8]
bang mau nanya nih, setelah saya klik tombol startnya hanya stuck di wait saja. kira2 apanya yang kurang ya bang? saya udah ikuti semua prosesnya. terima kasih pencerahannya bang.

**Comment by WhatsAppNETClient** [comment]
@gaul56

coba di restart om pc/laptopnya trus login pake user admin
